### ISSUE TITLE
Small patch

### ISSUE THREAD

**Issue by pflaeging** [rb-cohen/redmine_email_attach#1]
Hi,

I've forked the project and made two small changes / enhancements:
- construct the attachment name with timestamp (if you get more attachments this is handy)
- corrected the raw attachment to the extension .EML and mime-type message/rfc822 to open it easy with a mail program!

Thx

:peter

**Comment by arronwoods** [comment]
Hi Peter,

Thanks, looks great, have merged it into master. Very handy!

Arron
